# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import djangoplicity.archives.translation
import djangoplicity.metadata.archives.fields
import djangoplicity.translation.fields
import djangoplicity.translation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0028_auto_20201029_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('lang', djangoplicity.translation.fields.LanguageField(db_index=True, default=djangoplicity.translation.models._get_defaut_lang, max_length=7, verbose_name='Language')),
                ('translation_ready', models.BooleanField(default=False, help_text='When you check this box and save this translation, an automatic notification email will be sent.')),
                ('id', djangoplicity.metadata.archives.fields.AVMIdField(help_text='ID of the activity, also used in URLs', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('observatory', models.CharField(max_length=50)),
                ('meeting_point', models.CharField(max_length=100)),
                ('travel_info_url', models.URLField(help_text='Link to travel info page')),
                ('map_url', models.URLField(help_text='Link to Google Maps')),
                ('duration', models.DurationField(help_text='Format: HH:MM')),
                ('latest_reservation_time', models.IntegerField(default=24, help_text='Until how many hours before the start do we accept reservations')),
                ('min_participants', models.IntegerField(default=5, help_text='Min. no of participants')),
                ('max_participants', models.IntegerField(default=150, help_text='Max. no of participants')),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('key_visual_en', djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.Image', verbose_name='English poster')),
                ('key_visual_es', djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.Image', verbose_name='Spanish poster')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=80, verbose_name='Full name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('phone_chile', models.CharField(max_length=50, null=True, verbose_name='Phone in Chile')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('n_spaces', models.SmallIntegerField(verbose_name='Number of places')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Language', verbose_name='Preferred language')),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, help_text='If left empty will be calculated from the activity duration', null=True)),
                ('private', models.BooleanField(default=False, help_text='Whether the showing if private.')),
                ('max_spaces_per_reservation', models.SmallIntegerField(default=0, help_text='Maximum number of spaces per reservation, 0 for no maximum')),
                ('total_spaces', models.IntegerField(blank=True, help_text='Total number of seats (based on selected activity)')),
                ('free_spaces', models.IntegerField(blank=True, help_text='Current number of available seats (based on current resevations)')),
                ('activity', djangoplicity.translation.fields.TranslationForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='visits.Activity')),
                ('offered_languages', models.ManyToManyField(to='visits.Language')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='showing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Showing'),
        ),
        migrations.AddField(
            model_name='activity',
            name='offered_languages',
            field=models.ManyToManyField(to='visits.Language'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='visits.Activity', verbose_name='Translation source'),
        ),
        migrations.CreateModel(
            name='ActivityProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Activity translation',
                'proxy': True,
                'verbose_name_plural': 'Activity translations',
                'indexes': [],
            },
            bases=('visits.activity', djangoplicity.archives.translation.TranslationProxyMixin),
            managers=[
                ('translation_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
