# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-02 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='phone_chile',
        ),
        migrations.AddField(
            model_name='reservation',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternative Phone'),
        ),
    ]
