# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-10 18:24
from __future__ import unicode_literals

from django.db import migrations
import djangoplicity.metadata.archives.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20210610_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='conduct_form_text',
            field=djangoplicity.metadata.archives.fields.AVMDescriptionField(blank=True, help_text='Full caption and related description text for the image resource.', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='disclaimer_form_text',
            field=djangoplicity.metadata.archives.fields.AVMDescriptionField(blank=True, help_text='Full caption and related description text for the image resource.', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='safety_form_text',
            field=djangoplicity.metadata.archives.fields.AVMDescriptionField(blank=True, help_text='Full caption and related description text for the image resource.', null=True),
        ),
    ]
