# Generated by Django 3.1 on 2022-09-12 10:22

from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_auto_20210610_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='visits.activity', verbose_name='Translation source'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='visits.language', verbose_name='Preferred language'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='showing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='visits.showing'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='activity',
            field=djangoplicity.translation.fields.TranslationForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='showings', to='visits.activity'),
        ),
    ]
