# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-27 09:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import djangoplicity.visits.models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_auto_20210610_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='conduct_form_text',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='disclaimer_form_text',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='safety_form_text',
        ),
        migrations.AddField(
            model_name='activity',
            name='conduct_form_file',
            field=models.FileField(blank=True, null=True, upload_to=djangoplicity.visits.models.handle_uploaded_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='activity',
            name='disclaimer_form_file',
            field=models.FileField(blank=True, null=True, upload_to=djangoplicity.visits.models.handle_uploaded_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='activity',
            name='safety_form_file',
            field=models.FileField(blank=True, null=True, upload_to=djangoplicity.visits.models.handle_uploaded_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
