# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-03 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_showing_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='meeting_point_link',
            field=models.URLField(blank=True, help_text='Link to Meeting point', null=True),
        ),
    ]
