# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-03 19:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0015_auto_20211214_0933'),
        ('visits', '0008_activity_meeting_point_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='conduct_form_file',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='disclaimer_form_file',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='safety_form_file',
        ),
        migrations.AddField(
            model_name='activity',
            name='conduct_tech_doc',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products2.TechnicalDocument', verbose_name='Conduct Technical Doc'),
        ),
        migrations.AddField(
            model_name='activity',
            name='liability_tech_doc',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products2.TechnicalDocument', verbose_name='Liability Technical Doc'),
        ),
        migrations.AddField(
            model_name='activity',
            name='safety_tech_doc',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products2.TechnicalDocument', verbose_name='Safety Technical Doc'),
        ),
    ]
