# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-28 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_auto_20230117_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='vehicle_plate_required',
            field=models.BooleanField(default=False, verbose_name='Vehicle Plate is Required?'),
        ),
    ]
