# Generated by Django 3.1 on 2023-06-04 20:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djangoplicity.archives.translation
import djangoplicity.translation.fields
import djangoplicity.translation.models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0013_auto_20230502_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictionRecommendation',
            fields=[
                ('lang', djangoplicity.translation.fields.LanguageField(db_index=True, default=djangoplicity.translation.models._get_defaut_lang, max_length=7, verbose_name='Language')),
                ('translation_ready', models.BooleanField(default=False, help_text='When you check this box and save this translation, an automatic notification email will be sent.')),
                ('id', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=256, verbose_name='Icon Caption')),
                ('source', djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='visits.restrictionrecommendation', verbose_name='Translation source')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestrictionRecommendationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Restriction or Recommendation translation',
                'verbose_name_plural': 'Restrictions and Recommendations translations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('visits.restrictionrecommendation', djangoplicity.archives.translation.TranslationProxyMixin),
            managers=[
                ('translation_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='restrictions_and_recommendations',
            field=djangoplicity.translation.fields.TranslationManyToManyField(to='visits.RestrictionRecommendation'),
        ),
    ]
