# Generated by Django 3.1 on 2023-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0015_auto_20230604_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='require_age',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='age_range',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('6-12', '6-12 years old'), ('13-18', '13-18 years old'), ('18+', '18+ years old')], default='Unknown', max_length=10),
        ),
    ]
