# Generated by Django 3.1 on 2023-06-13 13:59

from django.db import migrations, models
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0016_auto_20230613_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='require_rut_number',
            field=models.BooleanField(default=False, help_text='RUT number required on the reservation form'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rut',
            field=models.IntegerField(default=0, verbose_name='RUT Number'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='require_age',
            field=models.BooleanField(default=False, help_text='Age range required on the reservation form'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='restrictions_and_recommendations',
            field=djangoplicity.translation.fields.TranslationManyToManyField(blank=True, to='visits.RestrictionRecommendation'),
        ),
    ]
