# Generated by Django 3.1 on 2023-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0018_auto_20230613_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rut',
            field=models.IntegerField(blank=True, default=0, verbose_name='RUT Number'),
        ),
    ]
