# Generated by Django 3.1 on 2023-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0021_auto_20230621_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='showing_list_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='related_activities',
            field=models.ManyToManyField(blank=True, related_name='_activity_related_activities_+', to='visits.Activity', verbose_name='Join with Activities'),
        ),
    ]
