# Generated by Django 3.1 on 2023-06-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0022_auto_20230622_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='showing_list_title_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
