# Generated by Django 3.1 on 2023-06-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0024_activity_join_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='join_name',
            field=models.CharField(blank=True, help_text='name to be displayed in the activity description when the activity is joined with other activities', max_length=100, null=True),
        ),
    ]
