# Generated by Django 3.1 on 2023-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0025_auto_20230622_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='join_name',
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, help_text='title to be displayed in the activity description when the activity is joined with other activities', max_length=100, null=True),
        ),
    ]
