# Generated by Django 3.1 on 2023-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0026_auto_20230622_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='RUT Number'),
        ),
    ]
