# Generated by Django 3.1 on 2024-05-02 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0028_auto_20230726_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.activity', verbose_name='Activity')),
                ('reservations', models.ManyToManyField(blank=True, to='visits.Reservation', verbose_name='Reservations')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.showing', verbose_name='Showing')),
            ],
            options={
                'verbose_name': 'Group Reservation',
                'verbose_name_plural': 'Group Reservations',
                'ordering': ['-showing__start_time'],
            },
        ),
    ]
