# Generated by Django 3.1 on 2024-05-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0029_groupreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupreservation',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
