# Generated by Django 3.1 on 2024-05-03 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0030_groupreservation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupreservation',
            options={'verbose_name': 'Group Reservation', 'verbose_name_plural': 'Group Reservations'},
        ),
        migrations.RemoveField(
            model_name='groupreservation',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='groupreservation',
            name='reservations',
        ),
        migrations.RemoveField(
            model_name='groupreservation',
            name='showing',
        ),
        migrations.AddField(
            model_name='activity',
            name='group_enable',
            field=models.BooleanField(default=False, help_text='Enable in group registration'),
        ),
        migrations.AddField(
            model_name='groupreservation',
            name='guests',
            field=models.TextField(blank=True, null=True, verbose_name='guests'),
        ),
        migrations.AddField(
            model_name='groupreservation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.activity', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='groupreservation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
