# Generated by Django 3.1 on 2024-05-03 08:24

from django.db import migrations
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0018_auto_20230502_2342'),
        ('visits', '0031_auto_20240503_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='group_liability_tech_doc',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products2.technicaldocument', verbose_name='Group Liability Technical Doc'),
        ),
        migrations.AddField(
            model_name='activity',
            name='group_liability_tech_doc_es',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products2.technicaldocument', verbose_name='Spanish Group Liability Technical Doc'),
        ),
        migrations.AddField(
            model_name='activity',
            name='group_safety_tech_doc',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products2.technicaldocument', verbose_name='Group Safety Technical Doc'),
        ),
        migrations.AddField(
            model_name='activity',
            name='group_safety_tech_doc_es',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products2.technicaldocument', verbose_name='Spanish Group Safety Technical Doc'),
        ),
    ]
