# Generated by Django 3.1 on 2024-05-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0032_auto_20240503_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupreservation',
            name='accept_disclaimer_form',
            field=models.BooleanField(default=False, verbose_name='Accept Disclaimer Form'),
        ),
        migrations.AddField(
            model_name='groupreservation',
            name='accept_safety_form',
            field=models.BooleanField(default=False, verbose_name='Accept Safety Form'),
        ),
    ]
