# Generated by Django 3.1 on 2025-02-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0033_auto_20240503_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.DurationField(blank=True, help_text='Format: HH:MM', null=True),
        ),
    ]
