# Generated by Django 3.1 on 2025-02-03 11:06

from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0021_auto_20250201_0908'),
        ('visits', '0034_auto_20250201_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='photo_release_form',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products2.technicaldocument', verbose_name='Photo and Publication Release Form'),
        ),
        migrations.AddField(
            model_name='activity',
            name='photo_release_form_es',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products2.technicaldocument', verbose_name='Spanish Photo and Publication Release Form'),
        ),
        migrations.AddField(
            model_name='activity',
            name='require_hawaii_drivers_license_number',
            field=models.BooleanField(default=False, help_text='Hawai’i Drivers License Number required on the reservation form'),
        ),
        migrations.AddField(
            model_name='activity',
            name='require_hawaii_state_id',
            field=models.BooleanField(default=False, help_text='Hawai’i State ID required on the reservation form'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='accept_photo_release_form',
            field=models.BooleanField(default=False, verbose_name='Accept Photo and Publication Release Form'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hawaii_drivers_license_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Hawai’i Drivers License Number'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hawaii_state_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Hawai’i State ID'),
        ),
    ]
