# Generated by Django 3.1 on 2025-02-03 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0035_auto_20250203_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Format: HH:MM'),
        ),
    ]
