# Generated by Django 3.1 on 2025-06-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0037_auto_20250616_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='visits.language', verbose_name='Preferred language'),
        ),
    ]
