# Generated by Django 3.1 on 2025-08-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0038_auto_20250627_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contact_emails_notify',
            field=models.TextField(blank=True, help_text='Comma-separated list of emails to notify about reservations updates.', verbose_name='Contact Emails To Notify About Reservations Updates'),
        ),
    ]
