# Generated by Django 3.1 on 2025-07-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0038_auto_20250627_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('alternative_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternative Phone')),
                ('n_spaces', models.SmallIntegerField(verbose_name='Number of places')),
                ('country', models.CharField(max_length=2, verbose_name='Country')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='visits.language', verbose_name='Preferred language')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.showing')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('showing', 'email')},
            },
        ),
    ]
