# Generated by Django 3.1 on 2025-08-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0038_auto_20250627_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_waiting_list',
            field=models.BooleanField(default=False, verbose_name='Waiting List'),
        ),
    ]
