# Generated by Django 3.1 on 2025-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0040_reservation_is_waiting_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='enable_waiting_list',
            field=models.BooleanField(default=False, help_text='Enable waiting list for this activity'),
        ),
    ]
