# Generated by Django 3.1 on 2026-04-10 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0041_activity_enable_waiting_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +1 555-0123). Only digits, spaces, and + - ( ) are allowed.', regex='^[0-9\\+\\-\\(\\) ]+$')], verbose_name='Alternative Phone'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='country',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid country name. No special symbols or numbers allowed.', regex='^[a-zA-Z\\s\\.\\-\\(\\)]+$')], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +1 555-0123). Only digits, spaces, and + - ( ) are allowed.', regex='^[0-9\\+\\-\\(\\) ]+$')], verbose_name='Phone'),
        ),
    ]
