# Generated by Django 3.1 on 2026-09-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0041_activity_enable_waiting_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='attendance_confirmed',
            field=models.BooleanField(default=False, help_text='Checked after calling the visitor. To say no, cancel the reservation', verbose_name='Attendance confirmed'),
        ),
    ]
