# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-15 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-id']},
        ),
    ]
