name: Djangoplicity Visits CI

on:
  push:
    branches: [master, develop, release/*]
  pull_request:
    branches: [master, develop, release/*]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [2.7, 3.9]

    services:
      postgres:
        image: postgres:10.5
        env:
          POSTGRES_DB: djangoplicity-visits
          POSTGRES_USER: djangoplicity-visits
          POSTGRES_PASSWORD: djangoplicity-visits
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-essential.txt
          pip install -r requirements/requirements-testing.txt
          pip install -r requirements/requirements-python${{matrix.python-version}}.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: |
          env DJANGO_SETTINGS_MODULE="test_project.settings" coverage run --source='.' manage.py test
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: Python${{ matrix.python-version }}
          env_vars: OS,PYTHON
